# Generated by Django 2.2.4 on 2020-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_auto_20200731_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_list',
            name='username',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
